CREATE TABLE if not exists articles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) not null,
  content text not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  version bigint default 0 not null
);

CREATE TABLE if not exists comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id integer not null,
  content text not null,
  created_at timestamp not null,
  constraint fk_comments_article
    foreign key (article_id)
      references articles(id)
      on delete cascade
);

CREATE TABLE if not exists tags (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) not null unique
);

CREATE TABLE if not exists article_tag (
  article_id integer not null,
  tag_id     integer not null,
  PRIMARY KEY (article_id, tag_id),
  constraint fk_article_tag_article
    foreign key (article_id)
      references articles(id)
      on delete cascade,
  constraint fk_article_tag_tag
    foreign key (tag_id)
      references tags(id)
      on delete cascade
);