CREATE TABLE if not exists articles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) not null,
  content text not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  version bigint default 0 not null
);