create table if not exists articles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) not null,
  content text not null,
  created_at timestamp not null,
  updated_at timestamp not null,
  version bigint default 0 not null
);

create table if not exists comments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id integer not null,
  content text not null,
  created_at timestamp not null,
  constraint fk_comments_article
    foreign key (article_id)
      references articles(id)
      on delete cascade
);

create table if not exists tags (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

create table if not exists article_tag (
  article_id BIGINT NOT NULL,
  tag_id     BIGINT NOT NULL,
  PRIMARY KEY (article_id, tag_id),
  CONSTRAINT fk_article_tag_article
    FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE,
  CONSTRAINT fk_article_tag_tag
    FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);